### ISSUE TITLE
Config file in example site missing the `title` field

### ISSUE THREAD

**Issue by yaardie** [CyrusYip/hugo-theme-yue#3]
e.g `title: Example Site`

**Comment by CyrusYip** [comment]
It's set under languages.

https://github.com/CyrusYip/hugo-theme-yue/blob/18a6758418fb729084477c7cba010124cde58779/exampleSite/hugo.yaml#L30-L36

https://github.com/CyrusYip/hugo-theme-yue/blob/18a6758418fb729084477c7cba010124cde58779/exampleSite/hugo.yaml#L63-L69
